/**
 * Shared fixtures for situation unit tests.
 */

import {
  PAYLOAD_VERSION,
  SITUATION_SCHEMA_VERSION,
  type SituationPayload,
} from "./situation_types";

/**
 * Minimal valid 2-handed preflop fold tree.
 */
export function minimalFoldSituation(
  overrides: Partial<SituationPayload> = {},
): SituationPayload {
  const startingStack = 200;
  const sb = 1;
  const bb = 2;
  return {
    payloadVersion: PAYLOAD_VERSION,
    schemaVersion: SITUATION_SCHEMA_VERSION,
    setupKey: "random|s2|stack200|sb1|bb2|ante0",
    setupMode: "random",
    seatCount: 2,
    smallBlind: sb,
    bigBlind: bb,
    ante: 0,
    startingStack,
    buttonSeat: 0,
    heroSeat: 0,
    lineup: [
      {
        seat: 0,
        archetype: "HERO",
        name: "Hero",
        startingStack,
      },
      {
        seat: 1,
        archetype: "TAG",
        name: "Alex",
        startingStack,
      },
    ],
    holeCards: [
      { seat: 0, cards: ["As", "Kd"] },
      { seat: 1, cards: ["Qc", "Tc"] },
    ],
    heroHand: ["As", "Kd"],
    runouts: [
      { street: "flop", cards: ["2c", "7d", "Jh"] },
      { street: "turn", cards: ["9s"] },
      { street: "river", cards: ["3h"] },
    ],
    rootNodeId: "root",
    title: "BTN faces BB raise",
    nodes: {
      root: {
        type: "scripted",
        id: "root",
        street: "preflop",
        pot: 0,
        stacks: [startingStack, startingStack],
        streetBets: [0, 0],
        board: [],
        foldedSeats: [],
        actions: [
          { seat: 0, kind: "POST_SB", amountTo: sb },
          { seat: 1, kind: "POST_BB", amountTo: bb },
        ],
        nextNodeId: "open",
      },
      open: {
        type: "hero",
        id: "open",
        street: "preflop",
        pot: sb + bb,
        stacks: [startingStack - sb, startingStack - bb],
        streetBets: [sb, bb],
        board: [],
        foldedSeats: [],
        toAct: 0,
        callAmount: bb - sb,
        minRaiseTo: bb * 2,
        actions: [
          {
            actionKey: "FOLD",
            kind: "FOLD",
            coaching: "Folding forfeits the small blind with a strong holding.",
            verdict: "incorrect",
            evDeltaBb: -1,
            optimalActionKey: "RAISE_100",
            nextNodeId: "term_check",
          },
          {
            actionKey: "CALL",
            kind: "CALL",
            amountTo: bb,
            coaching: "Calling completes the small blind.",
            verdict: "close",
            evDeltaBb: -0.3,
            optimalActionKey: "RAISE_100",
            nextNodeId: "villain_folds_limp",
          },
          {
            actionKey: "RAISE_100",
            kind: "RAISE",
            amountTo: bb * 2.5,
            sizingBucket: "100",
            coaching: "Open to about 2.5x from the button with this holding.",
            verdict: "correct",
            evDeltaBb: 0,
            optimalActionKey: "RAISE_100",
            nextNodeId: "face_3bet",
          },
          {
            actionKey: "ALL_IN",
            kind: "ALL_IN",
            amountTo: startingStack,
            sizingBucket: "ALL_IN",
            coaching:
              "Shoving raw is overkill; save the stack for better spots.",
            verdict: "incorrect",
            evDeltaBb: -5,
            optimalActionKey: "RAISE_100",
            nextNodeId: "villain_folds_shove",
          },
        ],
      },
      face_3bet: {
        type: "scripted",
        id: "face_3bet",
        street: "preflop",
        pot: bb * 2.5 + bb,
        stacks: [startingStack - bb * 2.5, startingStack - bb],
        streetBets: [bb * 2.5, bb],
        board: [],
        foldedSeats: [],
        actions: [{ seat: 1, kind: "RAISE", amountTo: bb * 8 }],
        nextNodeId: "hero_vs_3bet",
      },
      hero_vs_3bet: {
        type: "hero",
        id: "hero_vs_3bet",
        street: "preflop",
        pot: bb * 2.5 + bb * 8,
        stacks: [startingStack - bb * 2.5, startingStack - bb * 8],
        streetBets: [bb * 2.5, bb * 8],
        board: [],
        foldedSeats: [],
        toAct: 0,
        callAmount: bb * 8 - bb * 2.5,
        minRaiseTo: bb * 8 + (bb * 8 - bb * 2.5),
        actions: [
          {
            actionKey: "FOLD",
            kind: "FOLD",
            coaching:
              "Folding AK to a large 3-bet can be fine versus a nitty range.",
            verdict: "incorrect",
            evDeltaBb: -1,
            optimalActionKey: "RAISE_100",
            nextNodeId: "term_fold",
          },
          {
            actionKey: "CALL",
            kind: "CALL",
            amountTo: bb * 8,
            coaching: "Calling keeps AK in play; plan carefully for flops.",
            verdict: "close",
            evDeltaBb: -0.2,
            optimalActionKey: "RAISE_100",
            nextNodeId: "villain_folds_call",
          },
          {
            actionKey: "RAISE_100",
            kind: "RAISE",
            amountTo: bb * 20,
            sizingBucket: "100",
            coaching: "4-betting AK is standard versus wide 3-bet ranges.",
            verdict: "correct",
            evDeltaBb: 0,
            optimalActionKey: "RAISE_100",
            nextNodeId: "villain_folds_4bet",
          },
        ],
      },
      term_check: {
        type: "terminal",
        id: "term_check",
        reason: "fold",
        street: "preflop",
        board: [],
        foldedSeats: [0],
        stacks: [startingStack - sb, startingStack - bb],
        pot: sb + bb,
        winnerSeats: [1],
        heroNetChips: -sb,
        summary: "Hero folds the button.",
      },
      term_call_open: {
        type: "terminal",
        id: "term_call_open",
        reason: "fold",
        street: "preflop",
        board: [],
        foldedSeats: [1],
        stacks: [startingStack - bb, startingStack - bb],
        pot: bb * 2,
        winnerSeats: [0],
        heroNetChips: bb,
        summary: "Villain folds after hero completes.",
      },
      term_shove: {
        type: "terminal",
        id: "term_shove",
        reason: "fold",
        street: "preflop",
        board: [],
        foldedSeats: [1],
        stacks: [0, startingStack - bb],
        pot: startingStack + bb,
        winnerSeats: [0],
        heroNetChips: bb,
        summary: "Villain folds to shove.",
      },
      term_fold: {
        type: "terminal",
        id: "term_fold",
        reason: "fold",
        street: "preflop",
        board: [],
        foldedSeats: [0],
        stacks: [startingStack - bb * 2.5, startingStack - bb * 8],
        pot: bb * 2.5 + bb * 8,
        winnerSeats: [1],
        heroNetChips: -(bb * 2.5),
        summary: "Hero folds to 3-bet.",
      },
      term_call: {
        type: "terminal",
        id: "term_call",
        reason: "fold",
        street: "preflop",
        board: [],
        foldedSeats: [1],
        stacks: [startingStack - bb * 8, startingStack - bb * 8],
        pot: bb * 16,
        winnerSeats: [0],
        heroNetChips: bb * 8,
        summary: "Villain folds after hero calls the 3-bet.",
      },
      term_4bet: {
        type: "terminal",
        id: "term_4bet",
        reason: "fold",
        street: "preflop",
        board: [],
        foldedSeats: [1],
        stacks: [startingStack - bb * 20, startingStack - bb * 8],
        pot: bb * 20 + bb * 8,
        winnerSeats: [0],
        heroNetChips: bb * 8,
        summary: "Villain folds to 4-bet.",
      },
      villain_folds_limp: {
        type: "scripted",
        id: "villain_folds_limp",
        street: "preflop",
        pot: bb * 2,
        stacks: [startingStack - bb, startingStack - bb],
        streetBets: [bb, bb],
        board: [],
        foldedSeats: [],
        actions: [{ seat: 1, kind: "FOLD" }],
        nextNodeId: "term_call_open",
      },
      villain_folds_call: {
        type: "scripted",
        id: "villain_folds_call",
        street: "preflop",
        pot: bb * 16,
        stacks: [startingStack - bb * 8, startingStack - bb * 8],
        streetBets: [bb * 8, bb * 8],
        board: [],
        foldedSeats: [],
        actions: [{ seat: 1, kind: "FOLD" }],
        nextNodeId: "term_call",
      },
      villain_folds_shove: {
        type: "scripted",
        id: "villain_folds_shove",
        street: "preflop",
        pot: startingStack + bb,
        stacks: [0, startingStack - bb],
        streetBets: [startingStack, bb],
        board: [],
        foldedSeats: [],
        actions: [{ seat: 1, kind: "FOLD" }],
        nextNodeId: "term_shove",
      },
      villain_folds_4bet: {
        type: "scripted",
        id: "villain_folds_4bet",
        street: "preflop",
        pot: bb * 20 + bb * 8,
        stacks: [startingStack - bb * 20, startingStack - bb * 8],
        streetBets: [bb * 20, bb * 8],
        board: [],
        foldedSeats: [],
        actions: [{ seat: 1, kind: "FOLD" }],
        nextNodeId: "term_4bet",
      },
    },
    ...overrides,
  };
}
