/// Placeholder Firebase configuration for debug builds.
///
/// Generated by `flutterfire configure` in a real setup. This stub lets the
/// Android debug build compile without real Firebase credentials. Replace with
/// the output of `flutterfire configure` once the Firebase project is wired up.
library;

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for the current platform.
class DefaultFirebaseOptions {
  /// Returns the [FirebaseOptions] for the running platform.
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
      case TargetPlatform.windows:
      case TargetPlatform.linux:
      case TargetPlatform.fuchsia:
        return web;
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'placeholder-api-key',
    appId: '1:000000000000:android:0000000000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'live-poker-trainer-placeholder',
    storageBucket: 'live-poker-trainer-placeholder.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'placeholder-api-key',
    appId: '1:000000000000:ios:0000000000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'live-poker-trainer-placeholder',
    storageBucket: 'live-poker-trainer-placeholder.firebasestorage.app',
    iosBundleId: 'com.pokerlab.livePokerTrainer',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'placeholder-api-key',
    appId: '1:000000000000:web:0000000000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'live-poker-trainer-placeholder',
    storageBucket: 'live-poker-trainer-placeholder.firebasestorage.app',
    authDomain: 'live-poker-trainer-placeholder.firebaseapp.com',
  );
}
