#!/usr/bin/env python3
"""Synthesize the table sound effects in ``assets/sounds``.

Short physical table sounds (a card flick, a clay chip click, knuckles on
felt) are modal impacts, not music, so they are synthesized here rather than
generated by a model: noise bursts and damped resonant modes shaped by
exponential envelopes, run through biquad filters. That keeps every clip
deterministic, royalty free, and a few kilobytes.

Usage::

    python3 tool/gen_sfx.py
"""

from __future__ import annotations

import math
import pathlib
import random
import struct
import wave

REPO = pathlib.Path(__file__).resolve().parent.parent
OUT_DIR = REPO / "assets" / "sounds"
SAMPLE_RATE = 22050


def silence(seconds: float) -> list[float]:
    """A buffer of the given duration."""
    return [0.0] * int(SAMPLE_RATE * seconds)


def mix(target: list[float], source: list[float], at: float = 0.0) -> None:
    """Adds ``source`` into ``target`` starting at ``at`` seconds."""
    offset = int(at * SAMPLE_RATE)
    for i, value in enumerate(source):
        index = offset + i
        if 0 <= index < len(target):
            target[index] += value


def envelope(length: int, attack: float, decay: float) -> list[float]:
    """Fast-attack, exponential-decay amplitude envelope."""
    attack_samples = max(1, int(attack * SAMPLE_RATE))
    out = []
    for i in range(length):
        if i < attack_samples:
            amplitude = i / attack_samples
        else:
            t = (i - attack_samples) / SAMPLE_RATE
            amplitude = math.exp(-t / max(decay, 1e-4))
        out.append(amplitude)
    return out


def noise(seconds: float, seed: int) -> list[float]:
    """White noise burst."""
    rng = random.Random(seed)
    return [rng.uniform(-1.0, 1.0) for _ in range(int(seconds * SAMPLE_RATE))]


def mode(seconds: float, freq: float, decay: float, phase: float = 0.0) -> list[float]:
    """A single damped sinusoidal mode, as struck objects produce."""
    length = int(seconds * SAMPLE_RATE)
    out = []
    for i in range(length):
        t = i / SAMPLE_RATE
        out.append(math.sin(2 * math.pi * freq * t + phase) * math.exp(-t / decay))
    return out


def biquad(
    samples: list[float],
    freq: float,
    q: float,
    kind: str = "bandpass",
) -> list[float]:
    """Applies a single biquad section (RBJ cookbook coefficients)."""
    w0 = 2 * math.pi * freq / SAMPLE_RATE
    alpha = math.sin(w0) / (2 * q)
    cos_w0 = math.cos(w0)

    if kind == "bandpass":
        b0, b1, b2 = alpha, 0.0, -alpha
    elif kind == "lowpass":
        b0 = (1 - cos_w0) / 2
        b1 = 1 - cos_w0
        b2 = (1 - cos_w0) / 2
    elif kind == "highpass":
        b0 = (1 + cos_w0) / 2
        b1 = -(1 + cos_w0)
        b2 = (1 + cos_w0) / 2
    else:
        raise ValueError(f"unknown filter kind: {kind}")

    a0 = 1 + alpha
    a1 = -2 * cos_w0
    a2 = 1 - alpha

    b0, b1, b2, a1, a2 = b0 / a0, b1 / a0, b2 / a0, a1 / a0, a2 / a0

    out = []
    x1 = x2 = y1 = y2 = 0.0
    for x0 in samples:
        y0 = b0 * x0 + b1 * x1 + b2 * x2 - a1 * y1 - a2 * y2
        out.append(y0)
        x2, x1 = x1, x0
        y2, y1 = y1, y0
    return out


def apply_envelope(samples: list[float], attack: float, decay: float) -> list[float]:
    """Multiplies ``samples`` by an attack/decay envelope."""
    env = envelope(len(samples), attack, decay)
    return [s * e for s, e in zip(samples, env)]


def normalize(samples: list[float], peak: float = 0.82) -> list[float]:
    """Scales to ``peak`` and applies a short fade-out to avoid clicks."""
    high = max((abs(s) for s in samples), default=0.0)
    if high <= 0:
        return samples
    gain = peak / high
    out = [s * gain for s in samples]
    fade = min(len(out), int(0.006 * SAMPLE_RATE))
    for i in range(fade):
        out[len(out) - 1 - i] *= i / fade
    return out


def write_wav(name: str, samples: list[float]) -> None:
    """Writes 16-bit mono PCM to ``assets/sounds/<name>``."""
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    path = OUT_DIR / name
    frames = b"".join(
        struct.pack("<h", int(max(-1.0, min(1.0, s)) * 32767)) for s in samples
    )
    with wave.open(str(path), "wb") as out:
        out.setnchannels(1)
        out.setsampwidth(2)
        out.setframerate(SAMPLE_RATE)
        out.writeframes(frames)
    print(f"wrote {path.relative_to(REPO)} ({len(frames) // 1024} KB)")


def card_flick(seed: int, brightness: float = 3200.0) -> list[float]:
    """One card leaving the deck: a bright, very short noise swish."""
    raw = noise(0.10, seed)
    body = biquad(raw, brightness, 1.1)
    body = biquad(body, 900, 0.7, kind="highpass")
    return apply_envelope(body, 0.001, 0.022)


def chip_click(seed: int, pitch: float = 1.0) -> list[float]:
    """A clay chip landing on another: noise transient plus three modes."""
    transient = apply_envelope(
        biquad(noise(0.03, seed), 5200 * pitch, 0.9), 0.0005, 0.004
    )
    out = list(transient)
    for freq, decay, gain in (
        (1180 * pitch, 0.030, 1.0),
        (2360 * pitch, 0.018, 0.55),
        (3910 * pitch, 0.010, 0.30),
    ):
        partial = mode(0.06, freq, decay)
        mix(out, [s * gain * 0.5 for s in partial])
    return out


def build_deal() -> list[float]:
    """Two cards dealt to the hero, a beat apart."""
    out = silence(0.30)
    mix(out, card_flick(11), 0.0)
    mix(out, [s * 0.85 for s in card_flick(12, 2900)], 0.085)
    return normalize(out)


def build_chip() -> list[float]:
    """A small stack of chips pushed forward."""
    out = silence(0.26)
    for i, (at, pitch, gain) in enumerate(
        ((0.0, 1.0, 1.0), (0.032, 1.09, 0.8), (0.071, 0.94, 0.62))
    ):
        mix(out, [s * gain for s in chip_click(21 + i, pitch)], at)
    return normalize(out)


def build_knock() -> list[float]:
    """Knuckles on the felt to check: wooden thump plus a dry click."""
    out = silence(0.24)
    for freq, decay, gain in ((196, 0.075, 1.0), (327, 0.045, 0.6), (612, 0.020, 0.3)):
        mix(out, [s * gain for s in mode(0.20, freq, decay)])
    click = apply_envelope(biquad(noise(0.02, 31), 2400, 1.0), 0.0004, 0.005)
    mix(out, [s * 0.5 for s in click])
    return normalize(out, peak=0.78)


def build_fold() -> list[float]:
    """Cards slid away across the felt: a soft descending swish."""
    raw = noise(0.34, 41)
    # Sweep the band down so the cards read as moving away from the player.
    swept = []
    x1 = x2 = y1 = y2 = 0.0
    for i, x0 in enumerate(raw):
        progress = i / len(raw)
        freq = 2600 - 1500 * progress
        w0 = 2 * math.pi * freq / SAMPLE_RATE
        alpha = math.sin(w0) / (2 * 0.8)
        cos_w0 = math.cos(w0)
        a0 = 1 + alpha
        b0, b1, b2 = alpha / a0, 0.0, -alpha / a0
        a1, a2 = (-2 * cos_w0) / a0, (1 - alpha) / a0
        y0 = b0 * x0 + b1 * x1 + b2 * x2 - a1 * y1 - a2 * y2
        swept.append(y0)
        x2, x1 = x1, x0
        y2, y1 = y1, y0
    return normalize(apply_envelope(swept, 0.012, 0.085), peak=0.62)


def build_win() -> list[float]:
    """Pot pushed to the hero: a chip cascade under a soft major chime."""
    out = silence(0.85)
    rng = random.Random(7)
    for i in range(9):
        at = 0.0 + i * 0.045 + rng.uniform(0, 0.014)
        mix(out, [s * rng.uniform(0.5, 0.95) for s in chip_click(50 + i, rng.uniform(0.9, 1.18))], at)
    # Major-sixth chime: warm, congratulatory, not arcade-like.
    for freq, gain, at in ((880, 0.5, 0.05), (1320, 0.34, 0.09), (1760, 0.2, 0.13)):
        chime = apply_envelope(mode(0.6, freq, 0.30), 0.004, 0.28)
        mix(out, [s * gain for s in chime], at)
    return normalize(out, peak=0.85)


def main() -> None:
    """Writes every table SFX."""
    write_wav("deal.wav", build_deal())
    write_wav("chip.wav", build_chip())
    write_wav("knock.wav", build_knock())
    write_wav("fold.wav", build_fold())
    write_wav("win.wav", build_win())


if __name__ == "__main__":
    main()
